### ISSUE TITLE
Running procedure

### ISSUE THREAD

**Issue by shlokgilda** [piy0999/CreditSense#1]
Could you please explain how do we run the deep learning models? I am facing a few issues in running the models. A few of the issues were regarding the file names, but I have fixed those. However, I am still facing issues regarding the end-to-end working of the deep learning module.

**Comment by WaqasAliAbbasi** [comment]
Hi @shlokgilda, we have two models. I am assuming you want to run the first model which is used to calculate the credit score. Just install the packages in `ml_requirements.txt` in `/bank_node` and then look at `/bank_node/API/ml_helper.py` which has the function to calculate credit score using an already trained model (saved as `/Deep Learning Model/finalized_model.sav`).

**Comment by shlokgilda** [comment]
@WaqasAliAbbasi This helps a lot. 
Another question. I am trying to train my own model. Could you please help me go about doing that?
